language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs. See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install --upgrade setuptools
- python setup.py install
before_script:
- export TZ=Europe/Brussels
script: python setup.py test
deploy:
  provider: pypi
  user: benverbeken
  password:
    secure: QyyK2pEWyxmL2P9STdRFqbTWvzcoKprplaGRjZDNCrD8uGLQgNvxmIBWpTjPkbNsSzdRXCrt0ndjIIbKt+W7i6m7NqXNcoq4CXrVt01fGlQPzAMMyJRGEXmYEa7Ph/691RPBJziE91zSbxIUdby4so8Re42ZMq1lrnPySp4W7hqjshDx+N0kZKkycLpRPkD+GseD41UZpic6tT95nGEnd5wRG/RmLctS1TdUG9Ht9uOMKiSOQl5KfkRERI6N+ukKnCw4npxyTiwAUoQivS1cneF8IvHAmnzMTbXv0PBZ+4TTjmk/hCPWfVEow441ZNS90XSILTo0vk9MdVidXE8/f9BDtzgEAy/+Kim3++Axpd6XSTxAf55BVuO5fR+e7MNJ+3t6jl4CMQxXi+k4ZsWp/IURvOorxJDjBnPJytGA22icdjO4HmimF5uM7yH/wbrKjXQ4HlGVNFWNYd4jZzyCmEyyco5A6FamfocPV5dND/tydPdb++0FQ6zTzpqg0JVUgw8T5f/xEeSpTjLJbLZpDQoAExooKWuHYgKdfG1d4xHvZc9T18boCEBXjvQaBPJ576k0ivL1ovvxouuFL/uHuu7fk0mwUMl1u98TZum/BIHoNajYTdY7ni3DBDgNfoQf1oMs1UvgoOWWYBaKEAYpWOoHBN8M8N0CgCxF8CTSaOA=
  on:
    tags: true
    python: 3.6
